---
- name: Setting up backend with VDO
  remote_user: root
  hosts: vdos
  gather_facts: false

  vars:
     # Create a vdo
     gluster_infra_pvs: '/dev/vdb'

     # The vitualsize option while creating thinpool
     gluster_infra_lv_logicalvols:
        - { lvname: 'thin_lv1', lvsize: '500G' }
        - { lvname: 'thin_lv2', lvsize: '500G' }

     # Mount the devices
     gluster_infra_mount_devices:
        - { path: '/mnt/thinv1',   lv: 'thin_lv1' }
        - { path: '/mnt/thinv2',   lv: 'thin_lv2' }

  roles:
    - gluster.infra
