---
# CLI: ansible-playbook -i inventory vg_create.yml --tags vdocreate,vgcreate
- name: Setting up backend with VDO
  remote_user: root
  hosts: vdos
  gather_facts: false

  vars:
     # Create a vdo
     gluster_infra_vdo:
        - { name: 'foo', device: '/dev/vdb' }

     # Variables for creating volume group
     gluster_infra_vg_name: vdo_vg
     gluster_infra_disktype: RAID6

     # RAID6 and RAID10 diskcount
     gluster_infra_diskcount: 10
     gluster_infra_stripe_unit_size: 128

  roles:
    - gluster.infra
