---
# Only XFS is supported in GlusterFS

- name: Mount the devices
  mount:
     path: "{{ item.path }}"
     state: mounted
     fstype: xfs
     opts: "inode64,noatime,nodiratime"
     src: "/dev/{{gluster_infra_vg_name}}/{{item.lv}}"
  with_items: "{{ gluster_infra_mount_devices }}"
