---
# tasks to setup ctdb
# Ensure the packages are installed
- name: Check if necessary CTDB packages are installed
  package:
     name: "{{ item }}"
     state: present
  with_items: "{{ ctdb_packages }}"
  when: >
     ctdb_packages is defined and
     ctdb_packages | length > 0

- name: Creates /etc/ctdb directory
  file:
     path: /etc/ctdb
     state: directory

# Unfortunately ansible does not provide modules to empty the contents
#  of a file. We will remove the file and create a empty file.
- name: Remove nodes and public_addresses files
  file:
     path: "{{ item }}"
     state: absent
  with_items:
     - /etc/ctdb/nodes
     - /etc/ctdb/public_addresses

- name: Create files nodes and public_addresses
  file:
     path: "{{ item }}"
     state: touch
  with_items:
     - /etc/ctdb/nodes
     - /etc/ctdb/public_addresses

- name: Add nodes entry to /etc/ctdb/nodes
  lineinfile:
     dest: /etc/ctdb/nodes
     line: "{{ item }}"
  with_items: "{{ gluster_features_ctdb_nodes.split(',') }}"

- name: Add public address entries to /etc/ctdb/public_addresses
  lineinfile:
     dest: /etc/ctdb/public_addresses
     line: "{{ item }}"
  when: gluster_features_ctdb_publicaddr is defined
  with_items: "{{ gluster_features_ctdb_publicaddr.split(',') }}"

- name: Enable clustering in Samba
  lineinfile:
      dest: /etc/samba/smb.conf
      line: "clustering=yes"
      insertafter: '^\[global\]'

- name: Add volume name to ctdb setup/teardown scripts
  replace:
     dest: "{{ item }}"
     regexp: '^META="?all"?'
     replace: 'META="{{ gluster_features_ctdb_volume }}"'
  with_items:
      - /var/lib/glusterd/hooks/1/stop/pre/S29CTDB-teardown.sh
      - /var/lib/glusterd/hooks/1/start/post/S29CTDBsetup.sh
  ignore_errors: yes

# Restart the GlusterFS volume
- name: Stop GlusterFS volume
  gluster_volume:
     state: "{{ item }}"
     name: "{{ gluster_features_ctdb_volume }}"
  run_once: True
  with_items:
     - stopped
     - started

# - name: Enable and start ctdb service
#   service:
#      name: ctdb
#      enabled: yes
#      state: started

# Enable Samba for ctdb
- name: Add confs to glusterd.vol
  lineinfile:
      dest: /etc/glusterfs/glusterd.vol
      line: "    option rpc-auth-allow-insecure on"
      insertbefore: 'end-volume'

- name: Restart glusterd services
  service:
     name: glusterd
     state: restarted

- name: Create a new user
  user: name="{{ gluster_features_smb_username }}"
  when: gluster_features_smb_username is defined

- name: Set smb password
  raw: >
     (echo {{ gluster_features_smb_password }};
     echo {{ gluster_features_smb_password }}) | \
        smbpasswd -s -a "{{ gluster_features_smb_username }}"
  when: >
     gluster_features_smb_password is defined and
     gluster_features_smb_username is defined
