---
# tasks file for gluster.infra
- name: Add firewall rules
  import_role:
    name: "gluster.infra/roles/firewall_config"
  when: >
     gluster_infra_fw_ports is defined or
     gluster_infra_fw_services is defined
  tags:
    - firewall

- name: Configure the bricks
  import_role:
    name: "gluster.infra/roles/backend_setup"
  tags:
    - backend_setup
