galaxy_info:
  author: Devyani Kota
  description: https://github.com/devyanikota
  company: Red Hat Inc.

  license: GPLv3
  min_ansible_version: 2.5
  github_branch: master

  platforms:
  - name: Fedora
    versions:
      - all
  - name: RHEL
    versions:
      - 7.3 or above
  galaxy_tags:
    - cluster_volume
    - cluster_bricks

dependencies: []
